Add GA incentives
rewiringamerica/api.rewiringamerica.org pull request #328
Opened 2024-03-04 18:45 UTC by rpartridge

Adds Georgia incentives: https://docs.google.com/spreadsheets/d/1DH5Q6IzH-UhevG0jiQb7IrchU7GGkVsPoVMRTmS7tmU/edit#gid=995688950

I did end up doing a data refresh for these incentives since there were only 7, so the data should be up to date

2024-03-04 18:51 UTC, rpartridge commented on data/low_income_thresholds.json
> +  "GA": {
GA doesn't have any income-qualified programs but the schema test requires a default is filled out. This just uses the federal poverty guidelines

2024-03-05 18:41 UTC, datu925 requested changes
Thanks for doing the refresh. This needs a few changes mostly due to spreadsheet issues, but otherwise looks good.

2024-03-05 18:41 UTC, datu925 commented on data/GA/incentives.json
> +      "en": "Rebate for 50% of cost up to $250 for attic insulation. Addition of R-38 or greater required."
This should be type percentage with number 0.5, but the 250 maximum is correct.

Same true for all of the above (these are errors in the original spreadsheet).

2024-03-05 18:41 UTC, datu925 commented on data/GA/incentives.json
> +    "bonus_available": true
The data collector put some information in the "Bonus Details" column, but it all looks like it's related to how the incentives should be combined, which should go under Stacking Details instead.

1. Move the data into Stacking Details. Once Bonus Details is blank, `bonus_available` boolean will stop appearing when you rerun the script.
2. It looks like there is a maximum across several incentives, and we do have a way to represent that, but you'll need to add another file. See data/CO/incentive_relationships.json for an example of how to configure a maximum.

2024-03-06 15:39 UTC, datu925 requested changes
Almost there!

2024-03-06 15:39 UTC, datu925 commented on data/GA/incentive_relationships.json
Sorry, you also have to link them into (and configure as appropriate):
src/data/state_incentive_relationships.ts
test/data/schemas.test.ts

2024-03-06 16:34 UTC, rpartridge commented on data/GA/incentive_relationships.json
ahh right! fixed, thanks

2024-03-06 17:21 UTC, datu925 approved these changes

2024-03-06 17:31 UTC, merged